-- MySQL Script generated by MySQL Workbench
-- Wed Aug 29 21:15:27 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pipocadb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pipocadb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pipocadb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `pipocadb` ;

-- -----------------------------------------------------
-- Table `pipocadb`.`GENERO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pipocadb`.`GENERO` ;

CREATE TABLE IF NOT EXISTS `pipocadb`.`GENERO` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pipocadb`.`FILME`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pipocadb`.`FILME` ;

CREATE TABLE IF NOT EXISTS `pipocadb`.`FILME` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `descricao` VARCHAR(4000) NULL,
  `diretor` VARCHAR(60) NULL,
  `posterpath` VARCHAR(200) NULL,
  `popularidade` DECIMAL(10,2) NULL,
  `data_lancamento` DATE NULL,
  `id_genero` INT NOT NULL,
  PRIMARY KEY (`id`, `id_genero`),
  INDEX `fk_FILME_GENERO_idx` (`id_genero` ASC),
  CONSTRAINT `fk_FILME_GENERO`
    FOREIGN KEY (`id_genero`)
    REFERENCES `pipocadb`.`GENERO` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Insere os generos
-- -----------------------------------------------------
insert into GENERO (id, nome) values 
(1, 'Não Cadastrado'),
(28, 'Ação'),
(12, 'Aventura'),
(16, 'Animação'),
(35, 'Comédia'),
(80, 'Crime'),
(99, 'Documentário'),
(18, 'Drama'),
(10751, 'Família'),
(14, 'Fantasia'),
(36, 'História'),
(27, 'Horror'),
(10402, 'Musical'),
(9648, 'Mistério'),
(10749, 'Romance'),
(878, 'Ficção Científica'),
(10770, 'Filme para TV'),
(53, 'Suspense'),
(10752, 'Guerra'),
(37, 'Western');